### ISSUE TITLE
Missing values as NULL

### ISSUE THREAD

**Issue by jeroen** [mongosoup/rmongodb#44]
Not all missing values are handled appropriately. It might be better to convert them to bson `NULL` values.

```
> mongo.bson.from.list(list(num=c(pi, NA, NaN, Inf, -Inf), bool=c(T,F,NA), int=c(7L, NA), string=c("foo", NA)))
    num : 4      
        0 : 1    3.141593
        1 : 1    nan
        2 : 1    nan
        3 : 1    inf
        4 : 1    -inf

    bool : 4     
        0 : 8    true
        1 : 8    false
        2 : 8    true

    int : 4      
        0 : 16   7
        1 : 16   -2147483648

    string : 4   
        0 : 2    foo
        1 : 2    NA
```

**Comment by stanstrup** [comment]
This seem problematic. when you read the data back bson NULL is converted back to NULL which means you cannot use mongo.find.all with data.frame=TRUE which you cannot have NULL in your data.frame (length zero). Is there not a more proper bson NA? What was wrong with nan?
