### ISSUE TITLE
potential issue with mongo.bson.from.list

### ISSUE THREAD

**Issue by wolfgangh** [mongosoup/rmongodb#72]
Good day,

I experience an issue with the conversion of list objects to bson.
In my database I've stored historical data for multiple assets and funds (e.g. prices, net asset values, ...). The assets are identified by their bloomberg ticker stored in the key *ticker*.
Depending on the asset type there is either a key *LAST_PRICE | EUR* or a key *FUND_NET_ASSET_VALUES | EUR* (for mutual funds and etfs).

When I try to count all the entries in the database for a particular ticker using `mongo.count`, I get different results for JSON and list queries.

```R
lst_qry = list("ticker", "FUND_NET_ASSET_VAL|EUR")
lst_qry[["ticker"]] = "AVAITER GR Equity" 
lst_qry[["FUND_NET_ASSET_VAL|EUR"]] = list("$exits"=TRUE) 
from_list = mongo.bson.from.list(lst_qry)  

from_json = mongo.bson.from.JSON('{"ticker":"AVAITER GR Equity", "FUND_NET_ASSET_VAL|EUR":{"$exists":true}}')
```

Both objects seem to be identical:
```R
from_list
#	ticker : 2 	 AVAITER GR Equity
#	FUND_NET_ASSET_VAL|EUR : 3 	 
#		$exits : 8 	 true

from_json
#	ticker : 2 	 AVAITER GR Equity
#	FUND_NET_ASSET_VAL|EUR : 3 	 
#		$exists : 8 	 true
```

But when I now count the matches in the database I get 2034 hits using the former JSON object from_json (which is correct):
```R
mongo.count(mongo, db_collection, query=from_json)            # works
# [1] 2034
```
Using the former list object the result is *-1*:
```R
mongo.count(mongo, db_collection, query=from_list) 
#[1] -1
```
Any ideas what could cause this?

**Comment by dselivanov** [comment]
you have a mistake in word ```$exists``` :-)
```R
# your code
list("$exits"=TRUE) 
# rigth code
list("$exists"=TRUE) 
```
In fact, ```mongo.bson.from.JSON``` uses ```mongo.bson.from.list``` under the hood. Let me know if this helps.

**Comment by wolfgangh** [comment]
Hi Dmitriy,

thanks for the quick reply... You are right, the typo caused the difference... Now it works again ;-)
Thanks!

**Comment by dselivanov** [comment]
So I'm closing this.
