### ISSUE TITLE
Test framework?

### ISSUE THREAD

**Issue by georgeu2000** [mongosoup/rmongodb#90]
Not an issue, but I was curious why the tests don't use a test framework. Is there any special reason?

**Comment by dselivanov** [comment]
What do you mean by " test framework"? testthat package?

**Comment by georgeu2000** [comment]
I mean like R Unit https://cran.r-project.org/web/packages/RUnit/vignettes/RUnit.pdf .

Something that makes it easy to break up the functionality into individual tests.

**Comment by dselivanov** [comment]
Don't have an answer =) Most of the tests were wrote by Markus - previous maintainer. I'm not familiar with RUnit at all, on other projects use `testthat`.

**Comment by georgeu2000** [comment]
OK, thanks for the info.
