### ISSUE TITLE
Error: Authentication failed 

### ISSUE THREAD

**Issue by sunbarve** [mongosoup/rmongodb#98]
Trying to connect MongoDB on local machine using rmongodb

mongo <- mongo.create (host='127.0.0.1', username = "admin", password = "admin123", db = "admin")

Error: Authentication failed 
and using Ubuntu 16.04, R version 3.4.4 and MongoDB version: 3.2.19?

**Comment by dselivanov** [comment]
`rmongodb` package is abandoned - please use https://github.com/jeroen/mongolite
